apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: event-module
    tier: backend
  name: common

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-module
  name: event-module-deployment
  namespace: common
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: event-module
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: event-module
        release: r11082019
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: event-module-config
          image: gcr.io/bjp-saral/github.com/jarvisconsulting/event-module
          imagePullPolicy: Always
          name: event-module-container
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - envFrom:
            - configMapRef:
                name: event-module-config
          env:
            - name: QUEUE
              value: '*'
          args:
            - 'rake resque:work'
          command:
            - bundle
            - exec
          image: gcr.io/bjp-saral/github.com/jarvisconsulting/event-module
          imagePullPolicy: Always
          name: event-module-resque
          resources:
            limits:
              cpu: 2000m
              memory: 4048Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: redis
          image: redis:7.0.4
          imagePullPolicy: Always  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      nodeSelector:
        cloud.google.com/gke-nodepool: prod
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "prod"
          effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: event-module
  name: event-module-service
  namespace: common
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: event-module
  sessionAffinity: None
  type: LoadBalancer