apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: jumpstart-temp
    tier: backend
  name: jumpstart

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jumpstart-temp
  name: jumpstart-deployment-temp
  namespace: jumpstart
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jumpstart-temp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jumpstart-temp
        release: r11082019
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: jumpstart-config-temp
          image: gcr.io/bjp-saral/github.com/jarvisconsulting/jumpstart
          imagePullPolicy: IfNotPresent
          name: jumpstart-container-temp
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - envFrom:
            - configMapRef:
                name: jumpstart-config-temp
          args:
            - sidekiq
          command:
            - bundle
            - exec
          image: gcr.io/bjp-saral/github.com/jarvisconsulting/jumpstart
          imagePullPolicy: IfNotPresent
          name: jumpstart-config-temp-sidekiq
          resources:
            limits:
              cpu: 2000m
              memory: 4048Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: jumpstart-temp
  name: jumpstart-service-temp
  namespace: jumpstart
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: jumpstart-temp
  sessionAffinity: None
  type: LoadBalancer
